Repository lcobucci/jwt, pull requests merged in 2018-08, with the labels that each got.

#257 Fix PHP 5.5 compatibility
  src/Signer/Key.php
Labels: Bug

#258 Add Key typehint for verify()
  src/Signature.php
  src/Token.php
Labels: Documentation

#261 Adjust build
  .gitignore
  .travis.yml
  README.md
  composer.json
  composer.lock
  phpunit.xml.dist
  test/functional/EcdsaTokenTest.php
  test/functional/HmacTokenTest.php
  test/functional/RsaTokenTest.php
  test/functional/UnsignedTokenTest.php
  test/unit/BuilderTest.php
  test/unit/Claim/BasicTest.php
  test/unit/Claim/EqualsToTest.php
  test/unit/Claim/FactoryTest.php
  test/unit/Claim/GreaterOrEqualsToTest.php
  test/unit/Claim/LesserOrEqualsToTest.php
  test/unit/ParserTest.php
  test/unit/Parsing/DecoderTest.php
  test/unit/Parsing/EncoderTest.php
  test/unit/SignatureTest.php
  test/unit/Signer/BaseSignerTest.php
  test/unit/Signer/Ecdsa/KeyParserTest.php
  test/unit/Signer/Ecdsa/Sha256Test.php
  test/unit/Signer/Ecdsa/Sha384Test.php
  test/unit/Signer/Ecdsa/Sha512Test.php
  test/unit/Signer/EcdsaTest.php
  test/unit/Signer/Hmac/Sha256Test.php
  test/unit/Signer/Hmac/Sha384Test.php
  test/unit/Signer/Hmac/Sha512Test.php
  test/unit/Signer/HmacTest.php
  test/unit/Signer/KeyTest.php
  test/unit/Signer/KeychainTest.php
  test/unit/Signer/Rsa/Sha256Test.php
  test/unit/Signer/Rsa/Sha384Test.php
  test/unit/Signer/Rsa/Sha512Test.php
  test/unit/TokenTest.php
  test/unit/ValidationDataTest.php
Labels: Improvement
