Repository lcobucci/jwt, pull requests merged in 2020-12, with the labels that each got.

#591 Fix validation documentation
  docs/validating-tokens.md
Labels: Documentation

#595 Avoid conflicts with other polyfills
  compat/json-exception-polyfill.php
Labels: Bug

#600 Fix autoload.php path error
  docs/installation.md
Labels: Documentation

#601 Fix letter case error
  docs/configuration.md
Labels: Documentation

#555 Add StrictValidAt constraint, deprecate ValidAt to LooseValidAt
  docs/validating-tokens.md
  src/Validation/Constraint/LooseValidAt.php
  src/Validation/Constraint/StrictValidAt.php
  src/Validation/Constraint/ValidAt.php
  test/functional/UnsignedTokenTest.php
  test/unit/Validation/Constraint/LooseValidAtTest.php
  test/unit/Validation/Constraint/StrictValidAtTest.php
  test/unit/Validation/Constraint/ValidAtTest.php
  test/unit/Validation/Constraint/ValidAtTestCase.php
Labels: Improvement

#607 Fix typo in validating-tokens.md
  docs/validating-tokens.md
Labels: Documentation

#613 Prefer ext-sodium cache-timing-safe functions
  src/Encoding/CannotDecodeContent.php
  src/Encoding/JoseEncoder.php
  src/Signer/Key/InMemory.php
  test/performance/Hmac/HmacBench.php
  test/unit/Encoding/JoseEncoderTest.php
Labels: Improvement

#614 [CI] Lint composer.json
  .gitattributes
  .github/workflows/composer-json-lint.yml
  composer-require-checker.json
  composer.json
  composer.lock
Labels: CI
