Repository lcobucci/jwt, pull requests merged in 2020-11, with the labels that each got.

#508 Pull JOSE encoder back
  composer.json
  composer.lock
  src/Configuration.php
  src/Decoder.php
  src/Encoder.php
  src/Encoding/CannotDecodeContent.php
  src/Encoding/CannotEncodeContent.php
  src/Encoding/JoseEncoder.php
  src/Token/Builder.php
  src/Token/Parser.php
  test/functional/ES512TokenTest.php
  test/functional/EcdsaTokenTest.php
  test/functional/HmacTokenTest.php
  test/functional/MaliciousTamperingPreventionTest.php
  test/functional/RsaTokenTest.php
  test/functional/UnsignedTokenTest.php
  test/performance/Hmac/HmacBench.php
  test/unit/ConfigurationTest.php
  test/unit/Encoding/JoseEncoderTest.php
  test/unit/Token/BuilderTest.php
  test/unit/Token/ParserTest.php
Labels: Improvement

#454 Allow users to configure format for date registered claims
  docs/extending-the-library.md
  infection.json.dist
  src/ClaimsFormatter.php
  src/Configuration.php
  src/Encoding/ChainedFormatter.php
  src/Encoding/MicrosecondBasedDateConversion.php
  src/Encoding/UnifyAudience.php
  src/Token/Builder.php
  test/functional/ES512TokenTest.php
  test/functional/EcdsaTokenTest.php
  test/functional/HmacTokenTest.php
  test/functional/RsaTokenTest.php
  test/functional/UnsignedTokenTest.php
  test/unit/ConfigurationTest.php
  test/unit/Encoding/ChainedFormatterTest.php
  test/unit/Encoding/MicrosecondBasedDateConversionTest.php
  test/unit/Encoding/UnifyAudienceTest.php
  test/unit/Token/BuilderTest.php
Labels: Improvement

#524 Prevent BC-breaks
  .gitattributes
  .github/workflows/backwards-compatibility.yml
  roave-bc-check.yaml
Labels: CI, Improvement

#526 Minor improvements on docs and performance
  docs/extending-the-library.md
  infection.json.dist
  src/Builder.php
  src/Encoding/MicrosecondBasedDateConversion.php
  src/Encoding/UnifyAudience.php
  src/Parser.php
  src/Signer/OpenSSL.php
  src/Token/Builder.php
  src/Token/Parser.php
  test/unit/Encoding/MicrosecondBasedDateConversionTest.php
  test/unit/Token/ParserTest.php
Labels: Improvement

#531 Use lib exceptions
  Makefile
  docs/validating-tokens.md
  src/Builder.php
  src/Encoding/JoseEncoder.php
  src/Parser.php
  src/Signer.php
  src/Signer/CannotSignPayload.php
  src/Signer/Ecdsa/ConversionFailed.php
  src/Signer/Ecdsa/MultibyteStringConverter.php
  src/Signer/Ecdsa/SignatureConverter.php
  src/Signer/InvalidKeyProvided.php
  src/Signer/Key.php
  src/Signer/Key/FileCouldNotBeRead.php
  src/Signer/OpenSSL.php
  src/Token/Builder.php
  src/Token/InvalidTokenStructure.php
  src/Token/Parser.php
  src/Token/RegisteredClaimGiven.php
  src/Token/UnsupportedHeaderFound.php
  src/Validation/Constraint/LeewayCannotBeNegative.php
  src/Validation/Constraint/ValidAt.php
  src/Validation/RequiredConstraintsViolated.php
  src/Validation/Validator.php
  src/Validator.php
  test/functional/ES512TokenTest.php
  test/functional/EcdsaTokenTest.php
  test/functional/HmacTokenTest.php
  test/functional/RsaTokenTest.php
  test/functional/UnsignedTokenTest.php
  test/unit/Signer/Ecdsa/MultibyteStringConverterTest.php
  test/unit/Signer/KeyTest.php
  test/unit/Signer/RsaTest.php
  test/unit/Token/BuilderTest.php
  test/unit/Token/ParserTest.php
  test/unit/Validation/Constraint/ValidAtTest.php
  test/unit/Validation/RequiredConstraintsViolatedTest.php
  test/unit/Validation/ValidatorTest.php
Labels: Improvement

#533 Extract interface for keys
  docs/configuration.md
  docs/extending-the-library.md
  src/Configuration.php
  src/Signer/Ecdsa.php
  src/Signer/Hmac.php
  src/Signer/Key.php
  src/Signer/Key/FileCouldNotBeRead.php
  src/Signer/Key/LocalFileReference.php
  src/Signer/Key/SafeString.php
  src/Signer/Rsa.php
  test/_keys/Keys.php
  test/functional/ES512TokenTest.php
  test/functional/EcdsaTokenTest.php
  test/functional/HmacTokenTest.php
  test/functional/MaliciousTamperingPreventionTest.php
  test/functional/RFC6978VectorTest.php
  test/functional/RsaTokenTest.php
  test/functional/UnsignedTokenTest.php
  test/performance/Ecdsa/EcdsaBench.php
  test/performance/Hmac/HmacBench.php
  test/performance/NoneBench.php
  test/performance/Rsa/RsaBench.php
  test/unit/ConfigurationTest.php
  test/unit/Signer/EcdsaTest.php
  test/unit/Signer/HmacTest.php
  test/unit/Signer/Key/LocalFileReferenceTest.php
  test/unit/Signer/Key/SafeStringTest.php
  test/unit/Signer/KeyTest.php
  test/unit/Signer/NoneTest.php
  test/unit/Signer/RsaTest.php
  test/unit/Token/BuilderTest.php
  test/unit/Validation/Constraint/SignedWithTest.php
Labels: BC-break, Improvement

#536 Rename key implementation
  docs/configuration.md
  src/Configuration.php
  src/Signer/Key/InMemory.php
  test/functional/ES512TokenTest.php
  test/functional/EcdsaTokenTest.php
  test/functional/HmacTokenTest.php
  test/functional/MaliciousTamperingPreventionTest.php
  test/functional/RFC6978VectorTest.php
  test/functional/RsaTokenTest.php
  test/functional/UnsignedTokenTest.php
  test/performance/Hmac/HmacBench.php
  test/performance/NoneBench.php
  test/unit/ConfigurationTest.php
  test/unit/Signer/HmacTest.php
  test/unit/Signer/Key/InMemoryTest.php
  test/unit/Signer/NoneTest.php
  test/unit/Signer/RsaTest.php
  test/unit/Token/BuilderTest.php
  test/unit/Validation/Constraint/SignedWithTest.php
Labels: Improvement

#538 Rename getters
  docs/configuration.md
  docs/extending-the-library.md
  docs/issuing-tokens.md
  docs/parsing-tokens.md
  docs/validating-tokens.md
  src/Configuration.php
  src/Signer.php
  src/Signer/Ecdsa.php
  src/Signer/Ecdsa/Sha256.php
  src/Signer/Ecdsa/Sha384.php
  src/Signer/Ecdsa/Sha512.php
  src/Signer/Hmac.php
  src/Signer/Hmac/Sha256.php
  src/Signer/Hmac/Sha384.php
  src/Signer/Hmac/Sha512.php
  src/Signer/None.php
  src/Signer/OpenSSL.php
  src/Signer/Rsa.php
  src/Signer/Rsa/Sha256.php
  src/Signer/Rsa/Sha384.php
  src/Signer/Rsa/Sha512.php
  src/Token/Builder.php
  src/Validation/Constraint/SignedWith.php
  test/functional/ES512TokenTest.php
  test/functional/EcdsaTokenTest.php
  test/functional/HmacTokenTest.php
  test/functional/MaliciousTamperingPreventionTest.php
  test/functional/RsaTokenTest.php
  test/functional/UnsignedTokenTest.php
  test/unit/ConfigurationTest.php
  test/unit/Signer/Ecdsa/Sha256Test.php
  test/unit/Signer/Ecdsa/Sha384Test.php
  test/unit/Signer/Ecdsa/Sha512Test.php
  test/unit/Signer/EcdsaTest.php
  test/unit/Signer/Hmac/Sha256Test.php
  test/unit/Signer/Hmac/Sha384Test.php
  test/unit/Signer/Hmac/Sha512Test.php
  test/unit/Signer/HmacTest.php
  test/unit/Signer/NoneTest.php
  test/unit/Signer/Rsa/Sha256Test.php
  test/unit/Signer/Rsa/Sha384Test.php
  test/unit/Signer/Rsa/Sha512Test.php
  test/unit/Signer/RsaTest.php
  test/unit/Token/BuilderTest.php
  test/unit/Validation/Constraint/SignedWithTest.php
Labels: Improvement

#534 Final preparations for 4.0.0-beta1
  .github/workflows/backwards-compatibility.yml
  docs/configuration.md
  docs/upgrading.md
  mkdocs.yml
Labels: Documentation

#539 Backport custom exceptions
  compat/json-exception-polyfill.php
  composer.json
  src/Builder.php
  src/Encoding/CannotDecodeContent.php
  src/Encoding/CannotEncodeContent.php
  src/Exception.php
  src/Parser.php
  src/Parsing/Decoder.php
  src/Parsing/Encoder.php
  src/Signer/CannotSignPayload.php
  src/Signer/Ecdsa/ConversionFailed.php
  src/Signer/Ecdsa/MultibyteStringConverter.php
  src/Signer/InvalidKeyProvided.php
  src/Signer/Key.php
  src/Signer/Key/FileCouldNotBeRead.php
  src/Signer/OpenSSL.php
  src/Token/InvalidTokenStructure.php
  src/Token/RegisteredClaimGiven.php
  src/Token/RegisteredClaims.php
  src/Token/UnsupportedHeaderFound.php
  test/functional/EcdsaTokenTest.php
  test/functional/RsaTokenTest.php
  test/unit/BuilderTest.php
  test/unit/ParserTest.php
  test/unit/Parsing/DecoderTest.php
  test/unit/Parsing/EncoderTest.php
  test/unit/Signer/Ecdsa/MultibyteStringConverterTest.php
  test/unit/Signer/RsaTest.php
Labels: Backporting

#542 Backport new APIs
  compat/lcobucci-clock-polyfill.php
  composer.json
  src/Builder.php
  src/Claim/Factory.php
  src/Configuration.php
  src/Parser.php
  src/Signer/Key.php
  src/Signer/Key/InMemory.php
  src/Signer/Key/LocalFileReference.php
  src/Signer/None.php
  src/Token.php
  src/Token/DataSet.php
  src/Validation/Constraint.php
  src/Validation/Constraint/IdentifiedBy.php
  src/Validation/Constraint/IssuedBy.php
  src/Validation/Constraint/LeewayCannotBeNegative.php
  src/Validation/Constraint/PermittedFor.php
  src/Validation/Constraint/RelatedTo.php
  src/Validation/Constraint/SignedWith.php
  src/Validation/Constraint/ValidAt.php
  src/Validation/ConstraintViolation.php
  src/Validation/NoConstraintsGiven.php
  src/Validation/RequiredConstraintsViolated.php
  src/Validation/Validator.php
  src/Validator.php
  test/functional/CompatibilityLayerTest.php
  test/functional/EcdsaTokenTest.php
  test/functional/HmacTokenTest.php
  test/functional/RFC6978VectorTest.php
  test/functional/RsaTokenTest.php
  test/functional/UnsignedTokenTest.php
  test/unit/BuilderTest.php
  test/unit/ConfigurationTest.php
  test/unit/ParserTest.php
  test/unit/Signer/NoneTest.php
  test/unit/Token/DataSetTest.php
  test/unit/TokenTest.php
  test/unit/Validation/Constraint/ConstraintTestCase.php
  test/unit/Validation/Constraint/IdentifiedByTest.php
  test/unit/Validation/Constraint/IssuedByTest.php
  test/unit/Validation/Constraint/PermittedForTest.php
  test/unit/Validation/Constraint/RelatedToTest.php
  test/unit/Validation/Constraint/SignedWithTest.php
  test/unit/Validation/Constraint/ValidAtTest.php
  test/unit/Validation/RequiredConstraintsViolatedTest.php
  test/unit/Validation/ValidatorTest.php
Labels: Backporting

#543 Ensure compatibility with new token namespace
  roave-bc-check.yaml
  src/Builder.php
  src/Parser.php
  src/Signature.php
  src/Token.php
  src/Token/Plain.php
  src/Token/Signature.php
  test/functional/CompatibilityLayerTest.php
  test/functional/UnsignedTokenTest.php
  test/unit/BuilderTest.php
  test/unit/ParserTest.php
  test/unit/TokenTest.php
Labels: Backporting

#544 Only prefix file:// if doesn't exist already
  src/Signer/Key/LocalFileReference.php
  test/unit/Signer/Key/LocalFileReferenceTest.php
Labels: Improvement

#545 Only prefix file:// if doesn't exist already
  src/Signer/Key/LocalFileReference.php
  test/functional/CompatibilityLayerTest.php
Labels: Backporting

#547 Use arrays for audience
  src/Builder.php
  src/Claim/Factory.php
  src/Parser.php
  src/Token.php
  test/functional/CompatibilityLayerTest.php
  test/unit/BuilderTest.php
  test/unit/ParserTest.php
Labels: Backporting

#548 Final preparations for 3.4
  README.md
  docs/configuration.md
  docs/index.md
  docs/installation.md
  docs/issuing-tokens.md
  docs/parsing-tokens.md
  docs/upgrading.md
  docs/validating-tokens.md
  mkdocs.yml
  src/Builder.php
  src/Parser.php
  src/Signer/BaseSigner.php
  src/Signer/Ecdsa/MultibyteStringConverter.php
  src/Signer/Hmac.php
  src/Signer/OpenSSL.php
  src/Token.php
  src/ValidationData.php
  test/functional/CompatibilityLayerTest.php
  test/functional/EcdsaTokenTest.php
  test/functional/HmacTokenTest.php
  test/functional/RsaTokenTest.php
  test/functional/UnsignedTokenTest.php
  test/unit/BuilderTest.php
  test/unit/CheckForDeprecations.php
  test/unit/Signer/BaseSignerTest.php
  test/unit/Signer/HmacTest.php
  test/unit/TokenTest.php
Labels: Backporting

#549 Trigger autoloader for the class aliases
  compat/class-aliases.php
  composer.json
Labels: Bug

#562 Fix validation of the audience claim on the new API
  src/Token.php
  test/functional/CompatibilityLayerTest.php
  test/unit/TokenTest.php
  test/unit/Validation/Constraint/PermittedForTest.php
Labels: Bug

#561 Remove RegisteredClaimGiven exception in favour of deprecation message for withClaim
  src/Builder.php
  test/unit/BuilderTest.php
Labels: BC-break

#572 Update validating-tokens.md
  docs/validating-tokens.md
Labels: Documentation
