Repository lcobucci/jwt, pull requests merged in 2020-09, with the labels that each got.

#399 Move object initialisation to constructor
  docs/configuration.md
  infection.json.dist
  src/Configuration.php
  test/functional/ES512TokenTest.php
  test/functional/EcdsaTokenTest.php
  test/functional/HmacTokenTest.php
  test/functional/RsaTokenTest.php
  test/functional/UnsignedTokenTest.php
  test/unit/ConfigurationTest.php
Labels: Improvement

#429 Migrate to GH actions
  .gitattributes
  .github/workflows/benchmarks.yml
  .github/workflows/coding-standards.yml
  .github/workflows/mutation-tests.yml
  .github/workflows/phpunit.yml
  .github/workflows/static-analysis.yml
  .scrutinizer.yml
  .travis.yml
  README.md
Labels: CI, Improvement

#431 PHP 8.0 compatibility
  .github/workflows/phpunit.yml
  infection.json.dist
  phpstan.neon.dist
  src/Signer/OpenSSL.php
  test/unit/Signer/EcdsaTest.php
  test/unit/Signer/RsaTest.php
Labels: Improvement

#433 Backport GH actions
  .gitattributes
  .github/workflows/phpunit.yml
  .scrutinizer.yml
  .travis.yml
  README.md
Labels: CI

#432 Allow null value to getClaim method
  src/Token.php
  test/unit/TokenTest.php
Labels: Improvement

#422 Update `getPassphrase` PHPDoc
  src/Signer/Key.php
Labels: Improvement
