Repository lcobucci/jwt, pull requests merged in 2021-01, with the labels that each got.

#616 Expose interface that represents unencrypted tokens
  docs/extending-the-library.md
  docs/parsing-tokens.md
  docs/validating-tokens.md
  src/Token/Plain.php
  src/UnencryptedToken.php
  src/Validation/Constraint/SignedWith.php
  src/Validation/Constraint/StrictValidAt.php
Labels: Improvement

#624 Ignore mutations for now
  composer.lock
  infection.json.dist
Labels: CI

#617 Provide the UnixTimestampDates formatter
  docs/extending-the-library.md
  src/Encoding/ChainedFormatter.php
  src/Encoding/UnixTimestampDates.php
  test/unit/Encoding/ChainedFormatterTest.php
  test/unit/Encoding/UnixTimestampDatesTest.php
Labels: Improvement

#634 Fix argument name in `@param` annotation of `OpenSSL#doVerify()`
  src/Signer/OpenSSL.php
Labels: Bug, Documentation

#635 [v3.4] Token must expire the exact time of "exp" claim
  src/Token.php
  test/unit/TokenTest.php
  test/unit/Validation/Constraint/ValidAtTest.php
Labels: Bug

#636 Token must expire the exact time of "exp" claim
  src/Token/Plain.php
  test/unit/Token/PlainTest.php
  test/unit/Validation/Constraint/ValidAtTest.php
Labels: Bug

#632 Use the correct class name for in-memory keys in documentation
  docs/configuration.md
Labels: Documentation
