Repository lcobucci/jwt, pull requests merged in 2021-02, with the labels that each got.

#657 Migrate to native dependabot
  .github/dependabot.yml
  .github/workflows/merge-bot.yml
Labels: CI

#656 Fix forward compatibility layer gap for audience claim
  docs/upgrading.md
  src/Builder.php
  test/functional/CompatibilityLayerTest.php
  test/unit/TokenTest.php
Labels: Bug

#630 Improve deprecation for aud claims
  docs/upgrading.md
  src/Token.php
  test/unit/TokenTest.php
Labels: Documentation, Improvement

#667 Support composer classmap-authoritative option
  compat/class-aliases.php
  src/Token/Plain.php
  src/Token/Signature.php
Labels: Bug

#670 Fix compatibility issues with older libsodium version (< 1.0.14)
  infection.json.dist
  src/Encoding/CannotDecodeContent.php
  src/Encoding/JoseEncoder.php
  src/Signer/Key/InMemory.php
  src/SodiumBase64Polyfill.php
  test/functional/ES512TokenTest.php
  test/functional/EcdsaTokenTest.php
  test/functional/EddsaTokenTest.php
  test/functional/HmacTokenTest.php
  test/functional/MaliciousTamperingPreventionTest.php
  test/functional/RsaTokenTest.php
  test/functional/UnsignedTokenTest.php
  test/unit/Encoding/JoseEncoderTest.php
  test/unit/Signer/EddsaTest.php
  test/unit/Signer/Key/InMemoryTest.php
  test/unit/SodiumBase64PolyfillTest.php
Labels: Bug

#685 SodiumBase64Polyfill: fix fallback method reference
  src/SodiumBase64Polyfill.php
Labels: Bug
