Repository lcobucci/jwt, pull requests merged in 2022-08, with the labels that each got.

#864 Fix ecdsa key size validation
  src/Signer/CannotSignPayload.php
  src/Signer/Ecdsa.php
  src/Signer/Ecdsa/Sha256.php
  src/Signer/Ecdsa/Sha384.php
  src/Signer/Ecdsa/Sha512.php
  src/Signer/Ecdsa/UnsafeSha256.php
  src/Signer/Ecdsa/UnsafeSha384.php
  src/Signer/Ecdsa/UnsafeSha512.php
  src/Signer/InvalidKeyProvided.php
  src/Signer/OpenSSL.php
  src/Signer/Rsa.php
  src/Signer/UnsafeEcdsa.php
  src/Signer/UnsafeRsa.php
  test/_keys/Keys.php
  test/_keys/ecdsa/private_ec160.key
  test/_keys/ecdsa/public_ec160.key
  test/functional/ES512TokenTest.php
  test/functional/EcdsaTokenTest.php
  test/functional/RsaTokenTest.php
  test/performance/Ecdsa/EcdsaBench.php
  test/performance/Ecdsa/Sha256Bench.php
  test/performance/Ecdsa/Sha384Bench.php
  test/performance/Ecdsa/Sha512Bench.php
  test/performance/Ecdsa/private-256.key
  test/performance/Ecdsa/private-384.key
  test/performance/Ecdsa/private-521.key
  test/performance/Ecdsa/public-256.key
  test/performance/Ecdsa/public-384.key
  test/performance/Ecdsa/public-521.key
  test/unit/Signer/Ecdsa/Sha256Test.php
  test/unit/Signer/Ecdsa/Sha384Test.php
  test/unit/Signer/Ecdsa/Sha512Test.php
  test/unit/Signer/Ecdsa/UnsafeSha256Test.php
  test/unit/Signer/Ecdsa/UnsafeSha384Test.php
  test/unit/Signer/Ecdsa/UnsafeSha512Test.php
  test/unit/Signer/EcdsaTest.php
  test/unit/Signer/Rsa/Sha256Test.php
  test/unit/Signer/Rsa/Sha384Test.php
  test/unit/Signer/Rsa/Sha512Test.php
  test/unit/Signer/Rsa/UnsafeSha256Test.php
  test/unit/Signer/Rsa/UnsafeSha384Test.php
  test/unit/Signer/Rsa/UnsafeSha512Test.php
  test/unit/Signer/RsaTest.php
  test/unit/Signer/UnsafeEcdsaTest.php
  test/unit/Signer/UnsafeRsaTest.php
Labels: Improvement, Minor BC-break, Security

#832 Add Blake2b signature algorithm
  docs/configuration.md
  src/Signer/Blake2b.php
  test/performance/Blake2bBench.php
  test/unit/Signer/Blake2bTest.php
Labels: Improvement

#827 Add constraint for private claim validation
  docs/validating-tokens.md
  src/Validation/Constraint/CannotValidateARegisteredClaim.php
  src/Validation/Constraint/HasClaimWithValue.php
  test/unit/Validation/Constraint/HasClaimWithValueTest.php
Labels: Improvement

#865 Track constraint on violations
  src/Validation/Constraint/HasClaimWithValue.php
  src/Validation/Constraint/IdentifiedBy.php
  src/Validation/Constraint/IssuedBy.php
  src/Validation/Constraint/LooseValidAt.php
  src/Validation/Constraint/PermittedFor.php
  src/Validation/Constraint/RelatedTo.php
  src/Validation/Constraint/SignedWith.php
  src/Validation/Constraint/StrictValidAt.php
  src/Validation/ConstraintViolation.php
  test/functional/ES512TokenTest.php
  test/functional/EcdsaTokenTest.php
  test/functional/EddsaTokenTest.php
  test/functional/HmacTokenTest.php
  test/functional/MaliciousTamperingPreventionTest.php
  test/functional/RsaTokenTest.php
  test/functional/TimeFractionPrecisionTest.php
  test/functional/UnsignedTokenTest.php
  test/unit/JwtFacadeTest.php
  test/unit/Validation/Constraint/HasClaimWithValueTest.php
  test/unit/Validation/Constraint/IdentifiedByTest.php
  test/unit/Validation/Constraint/IssuedByTest.php
  test/unit/Validation/Constraint/PermittedForTest.php
  test/unit/Validation/Constraint/RelatedToTest.php
  test/unit/Validation/Constraint/SignedWithTest.php
  test/unit/Validation/Constraint/StrictValidAtTest.php
  test/unit/Validation/Constraint/ValidAtTest.php
  test/unit/Validation/Constraint/ValidAtTestCase.php
  test/unit/Validation/ConstraintViolationTest.php
Labels: Improvement

#866 Improve documentation
  docs/configuration.md
  docs/issuing-tokens.md
  docs/parsing-tokens.md
  docs/supported-algorithms.md
  docs/validating-tokens.md
  mkdocs.yml
Labels: Documentation

#872 Remove deprecated components
  .github/workflows/composer-json-lint.yml
  docs/supported-algorithms.md
  phpstan.neon.dist
  src/Signer/Ecdsa/UnsafeSha256.php
  src/Signer/Ecdsa/UnsafeSha384.php
  src/Signer/Ecdsa/UnsafeSha512.php
  src/Signer/Hmac/UnsafeSha256.php
  src/Signer/Hmac/UnsafeSha384.php
  src/Signer/Hmac/UnsafeSha512.php
  src/Signer/Key/LocalFileReference.php
  src/Signer/Rsa/UnsafeSha256.php
  src/Signer/Rsa/UnsafeSha384.php
  src/Signer/Rsa/UnsafeSha512.php
  src/Signer/UnsafeEcdsa.php
  src/Signer/UnsafeRsa.php
  src/Validation/Constraint/ValidAt.php
  test/functional/HmacTokenTest.php
  test/unit/Signer/Ecdsa/UnsafeSha256Test.php
  test/unit/Signer/Ecdsa/UnsafeSha384Test.php
  test/unit/Signer/Ecdsa/UnsafeSha512Test.php
  test/unit/Signer/Hmac/UnsafeSha256Test.php
  test/unit/Signer/Hmac/UnsafeSha384Test.php
  test/unit/Signer/Hmac/UnsafeSha512Test.php
  test/unit/Signer/Key/LocalFileReferenceTest.php
  test/unit/Signer/Rsa/UnsafeSha256.php
  test/unit/Signer/Rsa/UnsafeSha256Test.php
  test/unit/Signer/Rsa/UnsafeSha384Test.php
  test/unit/Signer/Rsa/UnsafeSha512Test.php
  test/unit/Signer/RsaTest.php
  test/unit/Signer/UnsafeEcdsaTest.php
  test/unit/Signer/UnsafeRsaTest.php
  test/unit/Validation/Constraint/ValidAtTest.php
Labels: Improvement, BC-break

#873 Use abstraction instead of concretion
  src/Builder.php
  src/Token/Builder.php
Labels: Improvement, BC-break

#874 Make method explicitly internal
  src/Signer/Ecdsa.php
Labels: Documentation, Minor BC-break

#879 fix typo : you must create a new token builder,
  docs/issuing-tokens.md
Labels: Documentation

#880 PHP Version constraint: stick to tested versions only
  composer.json
  composer.lock
Labels: Improvement

#882 Fix typo: you must create a new token builder
  docs/issuing-tokens.md
Labels: Documentation
