Repository lcobucci/jwt, pull requests merged in 2022-11, with the labels that each got.

#968 Deprecate Ecdsa create
  docs/configuration.md
  docs/upgrading.md
  infection.json.dist
  src/Signer/Ecdsa.php
  test/functional/ES512TokenTest.php
  test/functional/EcdsaTokenTest.php
  test/functional/MaliciousTamperingPreventionTest.php
  test/functional/RFC6978VectorTest.php
  test/performance/Ecdsa/Sha256Bench.php
  test/performance/Ecdsa/Sha384Bench.php
  test/performance/Ecdsa/Sha512Bench.php
  test/unit/Signer/Ecdsa/Sha256Test.php
  test/unit/Signer/Ecdsa/Sha384Test.php
  test/unit/Signer/Ecdsa/Sha512Test.php
Labels: Improvement, Minor BC-break

#938 Deprecate empty Signer, empty Key and empty Signature
  docs/configuration.md
  docs/upgrading.md
  phpstan.neon.dist
  src/Configuration.php
  src/Signer/Key/InMemory.php
  src/Signer/None.php
  src/Token/Signature.php
Labels: Improvement

#960 Setup Renovate as a replacement for Dependabot
  .github/dependabot.yml
  .github/workflows/merge-bot.yml
  renovate.json
Labels: Improvement, Dependencies
