Repository lcobucci/jwt, pull requests merged in 2023-02, with the labels that each got.

#998 Update to PHPUnit 10
  .gitignore
  composer.json
  composer.lock
  phpunit.xml.dist
  tests/RFC6978VectorTest.php
  tests/Signer/Ecdsa/EcdsaTestCase.php
  tests/Signer/Ecdsa/MultibyteStringConverterTest.php
  tests/Signer/Ecdsa/Sha256Test.php
  tests/Signer/Ecdsa/Sha384Test.php
  tests/Signer/Ecdsa/Sha512Test.php
  tests/SodiumBase64PolyfillTest.php
  tests/TimeFractionPrecisionTest.php
  tests/Token/ParserTest.php
  tests/Validation/Constraint/HasClaimWithValueTest.php
Labels: Dependencies

#979 Builder: make it immutable
  docs/extending-the-library.md
  docs/upgrading.md
  src/Builder.php
  src/JwtFacade.php
  src/Token/Builder.php
  tests/Token/BuilderTest.php
Labels: Improvement, BC-break

#999 Use roave/backward-compatibility-check directly
  .github/workflows/backwards-compatibility.yml
  .roave-backward-compatibility-check.json
  README.md
  roave-bc-check.yaml
Labels: CI

#1000 Update docs and CI files
  .gitattributes
  .github/CONTRIBUTING.md
  .github/workflows/backwards-compatibility.yml
  .github/workflows/benchmarks.yml
  .github/workflows/coding-standards.yml
  .github/workflows/composer-json-lint.yml
  .github/workflows/mutation-tests.yml
  .github/workflows/phpunit.yml
  .github/workflows/static-analysis.yml
  Makefile
Labels: Documentation, CI

#1001 Support other PSR-20 implementations
  composer.json
  composer.lock
  docs/configuration.md
  docs/quick-start.md
  docs/upgrading.md
  src/JwtFacade.php
  src/Validation/Constraint/LooseValidAt.php
  src/Validation/Constraint/StrictValidAt.php
  tests/JwtFacadeTest.php
Labels: Improvement
